### ISSUE TITLE
Version 2.77β15を安定版（Version 2.78）としてリリースしたい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_windows#486]
- 開発環境の構築
https://github.com/ryotayama/hayaemon_windows/blob/master/README.md

- 関連Issue
https://github.com/ryotayama/hayaemon_windows/issues/299
https://github.com/ryotayama/hayaemon_windows/issues/329
https://github.com/ryotayama/hayaemon_windows/issues/236

- 補足
XP版はMicrosoftのサポート終了に伴いVersion 2.77 β 14から配布をやめたので、作成不要。

**Comment by sugartarou** [comment]
開発環境構築しました。

@ryotayama 
今あるベータ版をそのまま正式版って銘打ってリリースするのが作業で認識あってます？

それとも関連issue全部実施が期待でしょうか？

**Comment by ryotayama** [comment]
関連Issueは対応済みのもので、ビルドの際に参考になるかも…？と思ったやつです💡

**Comment by sugartarou** [comment]
承知しました〜🫡

**Comment by sugartarou** [comment]
Visual Studio Community 2022でもVisual Studio Enterprise 2017でも
Hayaemon.slnを開いた段階で以下が出てくる。。
![image](https://github.com/ryotayama/hayaemon_windows/assets/32073583/32e36432-cccd-4b2f-8a9e-ec7eb6166e25)

**Comment by sugartarou** [comment]
```
プロジェクト タイプで必要な Visual Studio ワークロードがインストールされていることを確認します。 [ツール]>[ツールと機能を取得] を選択して、Visual Studio インストーラーを開きます。 Windows インストーラーまたは ClickOnce の場合、ワークロードは .NET デスクトップ開発または C++ でのデスクトップ開発です。

Windows インストーラーのプロジェクトの場合は、[Visual Studio Installer Projects 拡張機能](https://learn.microsoft.com/ja-jp/visualstudio/deployment/installer-projects-net-core?view=vs-2022)のインストールが必要になる場合があります。

プロジェクトが Flexera Software の InstallShield を使用して作成されている場合、インストールの修復が必要になる場合があります (これは Visual Studio のアップグレード後に発生する可能性があります)。

必要なコンポーネントをインストールしたら、Visual Studio を閉じて再度開き、プロジェクトを再読み込みします。
```

ここまではやったがSetup_jpは未だ互換性なし。。

**Comment by sugartarou** [comment]
■解決手順まとめ
Visual Studio 2022の場合
![image](https://github.com/ryotayama/hayaemon_windows/assets/32073583/dddc4be9-9fe2-44a0-aaa1-f260b49ec164)
![image](https://github.com/ryotayama/hayaemon_windows/assets/32073583/07b7c37f-cb3c-4d83-bb25-e88908ece686)
プロジェクト閉じてVSIXインストーラが起きてくるのでModify
![image](https://github.com/ryotayama/hayaemon_windows/assets/32073583/681a380e-e7d9-4521-a64a-ccc7fa33767c)

**Comment by sugartarou** [comment]
まとめたら環境構築手順にも追加予定。

**Comment by sugartarou** [comment]
Setup_jpを右クリックからビルドしたところで次のエラー
![image](https://github.com/ryotayama/hayaemon_windows/assets/32073583/55aa6404-3ca0-4d6d-b67f-8d9939690e03)
```
重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態	詳細
エラー	C2065	'LC_ALL': 定義されていない識別子です。	Hayaemon	G:\ユーザ\Documents\00_Develop\hayaemon\hayaemon_windows\App.cpp	133		
```

App.cppにinclude追加で解決
```C
#include <locale.h>
```
![image](https://github.com/ryotayama/hayaemon_windows/assets/32073583/f8580c57-40bc-493d-8ebc-5eee17450b60)

**Comment by sugartarou** [comment]
再ビルドで次のエラー
ライブラリ開けないって言ってるからgetlibs.batのほうのエラー原因かな。
一旦getlibs.batの解析に戻る。
```
重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態	詳細
エラー	LNK1181	入力ファイル 'libjpeg.lib' を開けません。	Hayaemon	G:\ユーザ\Documents\00_Develop\hayaemon\hayaemon_windows\LINK	1		
```

**Comment by sugartarou** [comment]
@ryotayama 
まだビルド通せてませんが、Readmeの記述で先にいくつか相談させてください。

・動作環境
> Windows XP 以降の OS に対応しています。

XP非対応にするとのことですが、この部分の記述はWindows 7以降のOSと記載しますか？
それともVista？10？
指定頂きたいです～

・インストール
>　インストーラはつけていませんので、適当な場所に解凍してください。

インストーラあるので↑の一文目を削除するだけで良いでしょうか？

・更新履歴

Version 2.77 β 15 開発版を2.78 安定版としてリリースしました。

とかで良いでしょうか？

**Comment by sugartarou** [comment]
> 再ビルドで次のエラー ライブラリ開けないって言ってるからgetlibs.batのほうのエラー原因かな。 一旦getlibs.batの解析に戻る。
> 
> ```
> 重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態	詳細
> エラー	LNK1181	入力ファイル 'libjpeg.lib' を開けません。	Hayaemon	G:\ユーザ\Documents\00_Develop\hayaemon\hayaemon_windows\LINK	1		
> ```

libjpegのエラーはgetlibs.batを直したことで解消していたが、bassenc_mp3.libがない。
```
重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態	詳細
エラー	LNK1181	入力ファイル 'bassenc_mp3.lib' を開けません。	Hayaemon	G:\ユーザ\Documents\00_Develop\hayaemon\hayaemon_windows\LINK	1		
```

**Comment by sugartarou** [comment]
そもそもbassenc_mp324をdownloadlibs.ps1でとってきてすらない。
なぜ。。？
https://www.un4seen.com/download.php?bassenc_mp324

**Comment by sugartarou** [comment]
> そもそもbassenc_mp324をdownloadlibs.ps1でとってきてすらない。 なぜ。。？ https://www.un4seen.com/download.php?bassenc_mp324
> 
> 考えてもどうせ分からないので脳死でdownloadlibsに追加することにする。

downloadlibsとcopylibsに追加して、再度getlibs実行したのでbassenc_mp3も生成されるようになったのでビルド通るようになった。

**Comment by sugartarou** [comment]
Hayaemonプロジェクトはビルド通るようになったが、
Setup_jpはまだだった。。
```
------ Starting pre-build validation for project 'Setup_jp' ------ 
ERROR: Invalid or unspecified target for shortcut '聞々ハヤえもん', located in 'User's Programs Menu'
ERROR: Invalid or unspecified target for shortcut '聞々ハヤえもん', located in 'User's Desktop'
ERROR: An error occurred while validating.  HRESULT = '80131509'
------ Pre-build validation for project 'Setup_jp' completed ------
```

**Comment by sugartarou** [comment]
Release_jpに切り替えてビルドしたら何事もなく通った。
![image](https://github.com/ryotayama/hayaemon_windows/assets/32073583/2798e852-70b6-480a-b9f8-237d7cc25a20)

```
========== ビルド: 成功 2、失敗 0、最新の状態 0、スキップ 0 ==========
=========== ビルド は 11:41 で完了し、46.532 秒 掛かりました ==========
```

**Comment by sugartarou** [comment]
ReleaseZIP.bat動かしてみたらreadmeとmanualのところの構成がbatの期待と異なっていたので修正した。

**Comment by ryotayama** [comment]
> XP非対応にするとのことですが、この部分の記述はWindows 7以降のOSと記載しますか？
> 
> それともVista？10？
> 
> 指定頂きたいです～

サポート期限の切れたOSを動作保証対象にするのも厳しいから、
10以降にしちゃおうか！

> インストーラあるので↑の一文目を削除するだけで良いでしょうか？

ＯＫです！👍

> ・更新履歴
> 
> 
> 
> Version 2.77 β 15 開発版を2.78 安定版としてリリースしました。
> 
> 
> 
> とかで良いでしょうか？

ＯＫです！👍
